package org.thes.web;

import java.util.ArrayList;
import java.util.List;

import org.thes.dao.ArticleRepository;
import org.thes.dao.UtilisateurRepository;
import org.thes.dao.FavorisRepository;
import org.thes.entities.Article;
import org.thes.entities.Favoris;
import org.thes.entities.LigneFavoris;
import org.thes.entities.Utilisateur;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;


@Controller // This means that this class is a Controller
public class ArticleController {

	List<Article> pageArticlesPanier = new ArrayList<>();
	private double prixTotal = 0;
	
	List<Article> pageFavoris = new ArrayList<>();
	private FavorisRepository favorisRepository; 

	@Autowired // This means to get the bean called UtilisateurRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ArticleRepository articleRepository;
	

	@Autowired
	private UtilisateurRepository utilisateurRepository;

	@GetMapping(path="/articles")
	public String articles(Model model, @RequestParam(name="page", defaultValue = "0")int page,
										@RequestParam(name="size", defaultValue="9") int size,
										@RequestParam(name="motCle", defaultValue="") String motCle ) {

		Page<Article> pageArticles=articleRepository.findByLibelleContains(motCle,PageRequest.of(page, size));
		model.addAttribute("pageArticles", pageArticles);
		model.addAttribute("currentPage", page);
		model.addAttribute("size", size);
		model.addAttribute("motCle", motCle);
		model.addAttribute("pages", new int[pageArticles.getTotalPages()]);
		return "articles";
	}

	//Méthode panier
	@GetMapping(path="/AjoutPanier")
	public String panier(Model model,Long idArticle){
		if (idArticle != null) { 
			Article pageArticlesPanierLoc= articleRepository.getOne(idArticle);
			pageArticlesPanier.add(pageArticlesPanierLoc);
			prixTotal = prixTotal + pageArticlesPanierLoc.getPrixUnitaire(); //
			model.addAttribute("pageArticlesPanier", pageArticlesPanier);
			model.addAttribute("prixTotal", prixTotal);
			return "panier";
		}

		else { 
			model.addAttribute("pageArticlesPanier", pageArticlesPanier);
			model.addAttribute("prixTotal", prixTotal);
			return "panier"; 
		}
	}
	
	@GetMapping(path="/deleteArticlePanier")
	public String deletePanier(Model model, Long id) {
		for(int i=0 ; i < pageArticlesPanier.size();i++) { 
			if (id == pageArticlesPanier.get(i).getId_article()) {  // 
				prixTotal = prixTotal - pageArticlesPanier.get(i).getPrixUnitaire();
				pageArticlesPanier.remove(i);
			}	  
		}
		model.addAttribute("pageArticlesPanier", pageArticlesPanier);
		model.addAttribute("prixTotal", prixTotal);
		return "panier";
	}

	@RequestMapping(value="/")
	public String home() {
		return "redirect:/articles";
	}
	
	@GetMapping(path="/inscription") 
	public String inscription(Model model){
		return "inscription";
	} 
	
	@PostMapping(path="/saveUtilisateur") 
	public String inscription(String lastname,String firstname, String mail, String address, String tel, String username, String password){
		utilisateurRepository.save(new Utilisateur(null,username,password,firstname,lastname,address,mail,tel, null, null));
		return "redirect:/connexion";
	}
	
	/*===========================*/
	@GetMapping(path="/profil") 
	public String profil(Model model){
		return "profil";
	} 
	
	@GetMapping(path="/connexion") 
	public String login(Model model){
		return "connexion";
	} 

	@GetMapping(path="/deleteArticle")
	public String delete(Long id, String motCle, String page, String size) {
		articleRepository.deleteById(id);
		return "redirect:/articles?page="+page+"&motCle="+motCle+"&size="+size;
	}

	@GetMapping(path="/paiement")
	public String payment (Model model){
		model.addAttribute("prixTotal", prixTotal);
		return "paiement";
	}
  
  @GetMapping(path="/ajoutArticle") 
	public String ajoutArticle(Model model){
		return "ajoutArticle";
	}
	
	@PostMapping(path="/saveArticle") 
	public String saveArticle(String libelle, String description, double prix, String image){
		articleRepository.save(new Article(null,libelle,description,prix,image,null));
		return "redirect:/articles";
	} 
	
	//Méthode favoris 
	@GetMapping(path="/AjoutFavoris")
	public String ajoutFavoris(Model model, Long idArticle) {

		if (idArticle != null) { 

			Article pageFavoriAffiche = articleRepository.getOne(idArticle);
			pageFavoris.add(pageFavoriAffiche);

			model.addAttribute("pageFavoris", pageFavoris);
		
			return "favoris";
		}


		else { 
			model.addAttribute("pageFavoris", pageFavoris);
			return "favoris"; 
		}
	}
	
	@GetMapping(path="/deleteFavoris")
	public String deleteFavoris(Model model, Long id) {
		for(int i=0 ; i < pageFavoris.size();i++) { 
			if (id == pageFavoris.get(i).getId_article()) {  // 
				//prixTotal = prixTotal - pageArticlesPanier.get(i).getPrixUnitaire();
				pageFavoris.remove(i);
			}	  
		}
		model.addAttribute("pageFavoris", pageFavoris);
		
		return "favoris";
	}
	
}